import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {mkdtempSync,readFileSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const app='comp4020-final-ray0766',tag=(process.env.GITHUB_SHA??'local').slice(0,12)+'-'+(process.env.GITHUB_RUN_ID??Date.now());
if(!/^[a-z0-9-]+$/.test(tag))throw Error('Invalid release identifier');
const local=mkdtempSync(join(tmpdir(),'crit8-preflight-')),remote='/tmp/crit8-preflight-'+tag,backup='/data/release-backups/'+tag;
function run(cmd,args){const p=spawnSync(cmd,args,{encoding:'utf8',maxBuffer:8*1024*1024});if(p.status!==0)throw Error(cmd+' failed: '+p.stderr.slice(-2500));return p.stdout;}
// Wake only the existing app. Nothing in this script creates a Machine/volume.
await globalThis.fetch('https://'+app+'.fly.dev/healthz');
const machines=JSON.parse(run('flyctl',['machine','list','-a',app,'--json']));if(machines.length!==1)throw Error('Expected exactly one existing app machine');const machine=machines[0],id=machine.id,config=machine.config;
if(config.guest?.memory_mb!==256||config.guest?.cpus!==1||config.guest?.cpu_kind!=='shared'||config.mounts?.length!==1)throw Error('Unexpected machine allocation');
function exec(code){const command='node --input-type=module -e "await import(\'data:text/javascript;base64,'+Buffer.from(code).toString('base64')+'\')"';const result=JSON.parse(run('flyctl',['machine','exec',id,command,'-a',app,'--json','--timeout','120']));if(Number(result.exit_code??result.exitCode??0)!==0)throw Error('Remote operation failed: '+(result.stderr??'').split('\n').filter(l=>/^[A-Za-z]*Error:/.test(l)).slice(-2).join(' '));if(result.stdout!==undefined&&typeof result.stdout!=='string')throw Error('Invalid remote stdout');return result.stdout??'';}
const metadata={tag,machine:id,image:config.image,guest:config.guest,mounts:config.mounts,backup:backup+'/before.sqlite',candidateCommit:process.env.GITHUB_SHA??null};
const summary=exec(`const {DatabaseSync}=await import('node:sqlite');const fs=await import('node:fs');const {createHash}=await import('node:crypto');fs.mkdirSync(${JSON.stringify(backup)},{recursive:true,mode:0o700});fs.mkdirSync(${JSON.stringify(remote)},{recursive:true,mode:0o700});const db=new DatabaseSync('/data/little-post.sqlite');db.exec('PRAGMA busy_timeout=10000');db.prepare('VACUUM INTO ?').run(${JSON.stringify(backup+'/before.sqlite')});db.close();const copy=new DatabaseSync(${JSON.stringify(backup+'/before.sqlite')},{readOnly:true});const integrity=copy.prepare('PRAGMA integrity_check').get().integrity_check;if(integrity!=='ok')throw Error('Backup integrity failed');const schema=copy.prepare('PRAGMA user_version').get().user_version;copy.close();const sha256=createHash('sha256').update(fs.readFileSync(${JSON.stringify(backup+'/before.sqlite')})).digest('hex');fs.writeFileSync(${JSON.stringify(backup+'/machine-config.json')},${JSON.stringify(JSON.stringify(config))},{mode:0o600});fs.writeFileSync(${JSON.stringify(backup+'/metadata.json')},JSON.stringify({...${JSON.stringify(metadata)},schema,sha256}),{mode:0o600});fs.chmodSync(${JSON.stringify(backup+'/before.sqlite')},0o600);console.log(JSON.stringify({...${JSON.stringify(metadata)},schema,sha256,bytes:fs.statSync(${JSON.stringify(backup+'/before.sqlite')}).size,integrity}));`);
console.log('LIVE_BACKUP '+summary.trim());
// Source only; use the identical existing production dependencies on the VM.
run('tar',['-czf',join(local,'candidate.tgz'),'src','package.json','scripts/release/probe.mjs','scripts/release/sqlite-check.mjs']);const archive=readFileSync(join(local,'candidate.tgz'));
exec(`(await import('node:fs')).writeFileSync(${JSON.stringify(remote+'/candidate.tgz')},'');`);
for(let i=0;i<archive.length;i+=24000)exec(`(await import('node:fs')).appendFileSync(${JSON.stringify(remote+'/candidate.tgz')},Buffer.from('${archive.subarray(i,i+24000).toString('base64')}','base64'));`);
const transport=exec(`const fs=await import('node:fs');const {createHash}=await import('node:crypto');const {spawnSync,execFileSync}=await import('node:child_process');const {gunzipSync}=await import('node:zlib');const archive=fs.readFileSync(${JSON.stringify(remote+'/candidate.tgz')});const actual=createHash('sha256').update(archive).digest('hex');if(actual!=='${createHash('sha256').update(archive).digest('hex')}'||archive.length!==${archive.length})throw Error('Candidate transfer size/hash mismatch');const probe=spawnSync('tar',['-tzf',${JSON.stringify(remote+'/candidate.tgz')}],{encoding:'utf8'});const bytes=gunzipSync(archive);fs.writeFileSync(${JSON.stringify(remote+'/candidate.tar')},bytes);try{execFileSync('tar',['-xf',${JSON.stringify(remote+'/candidate.tar')},'-C',${JSON.stringify(remote)}]);}catch(e){throw Error('Candidate tar extraction: '+String(e.stderr).slice(0,700));}console.log(JSON.stringify({compressedBytes:archive.length,sha256:actual,tarBytes:bytes.length,gzipTarExit:probe.status,gzipTarError:probe.status===0?'':String(probe.stderr).trim().slice(0,700),uncompressedTar:'extracted'}));`);
console.log('CANDIDATE_TRANSPORT '+transport.trim());
const report=exec(`const fs=await import('node:fs');const {execFileSync}=await import('node:child_process');fs.symlinkSync('/app/node_modules',${JSON.stringify(remote+'/node_modules')},'dir');fs.copyFileSync(${JSON.stringify(backup+'/before.sqlite')},${JSON.stringify(remote+'/source.sqlite')});const output=execFileSync('node',['scripts/release/probe.mjs','source.sqlite'],{cwd:${JSON.stringify(remote)},env:{...process.env,NODE_OPTIONS:'--max-old-space-size=80'},encoding:'utf8'});fs.copyFileSync(${JSON.stringify(remote+'/source.sqlite.probe-result.json')},${JSON.stringify(backup+'/probe-result.json')});console.log(output.trim());`);
console.log('LIVE_MIGRATION_PROBE '+report.trim());writeFileSync(join(local,'summary.json'),JSON.stringify({backup:JSON.parse(summary),probe:JSON.parse(report)},null,2));
if(process.env.GITHUB_STEP_SUMMARY)writeFileSync(process.env.GITHUB_STEP_SUMMARY,'## Crit 8 live backup and migration preflight\n\n```json\n'+JSON.stringify({backup:JSON.parse(summary),probe:JSON.parse(report)},null,2)+'\n```\n',{flag:'a'});
console.log('Private database and original machine config remain only on the existing Fly volume. No database artifact uploaded.');
