import {test,expect} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
import {menuAction,readUniverse,closeVisit} from './flight-helper.ts';
const evidence='docs/evidence/history';
test('owner builds and replays privately without writing back; phone replay and visitor APIs stay isolated',async({browser})=>{
 test.setTimeout(120_000);mkdirSync(evidence,{recursive:true});const errors:string[]=[],checks:string[]=[];
 const context=await browser.newContext({storageState:'.data/physics-browser-owner.json',viewport:{width:1920,height:1080}});const page=await context.newPage();page.setDefaultTimeout(12_000);page.on('pageerror',e=>errors.push(e.message));let planet:string;
 try{
 await page.goto('/');await expect(page.locator('#scene-sync')).toContainText('Live');const original=(await readUniverse(page)).currentPlanet;planet=original.id;
 const start=await(await page.request.get('/api/history?planetId='+planet)).json();await menuAction(page,'build-mode');await page.waitForTimeout(850);await page.getByRole('button',{name:'Add lamp',exact:true}).click();
 const points=[[820,740],[1120,725],[700,620],[1230,650],[920,550],[1060,540]];let first=-1;
 for(let i=0;i<points.length;i++){await page.mouse.click(...points[i] as [number,number]);if(await page.locator('#save-object').isEnabled()){first=i;break;}}
 await expect(page.locator('#save-object')).toBeEnabled();await page.locator('#save-object').click();await expect(page.locator('#object-tools')).not.toBeVisible();const lamp=(await readUniverse(page)).currentPlanet.objects.find(o=>!original.objects.some(b=>b.id===o.id))!;expect(lamp).toBeTruthy();
 await page.locator('#built-list').selectOption(lamp.id);await page.locator('#rotate-object').click();await page.locator('#move-object').click();
 for(let i=points.length-1;i>=0;i--){if(i===first)continue;await page.mouse.click(...points[i] as [number,number]);if(await page.locator('#save-object').isEnabled())break;}
 await page.locator('#save-object').click();await expect(page.locator('#object-tools')).not.toBeVisible();await page.locator('#built-list').selectOption(lamp.id);await page.locator('#remove-object').click();await expect(page.locator('#object-tools')).not.toBeVisible();await page.locator('#finish-building').click();
 const final=await(await page.request.get('/api/history?planetId='+planet)).json();expect(final.head-start.head).toBe(4);const live=(await readUniverse(page)).currentPlanet.objects;expect(live).toEqual(original.objects);checks.push('real UI create, move+rotate, delete append exactly four events');
 await menuAction(page,'open-history');await expect(page.locator('#hy-status')).toContainText('live world unchanged');const canvas=page.locator('#hy-stage canvas');await expect(canvas).toHaveAttribute('data-sequence',String(final.head));await page.locator('#hy-previous').click();await expect(canvas).toHaveAttribute('data-object-count',String(live.length+1));await page.screenshot({path:`${evidence}/desktop-replay.png`});
 await page.locator('#hy-start').click();await expect(canvas).toHaveAttribute('data-sequence','0');await expect(page.locator('#hy-baseline')).toContainText('Earlier actions were not recorded');await page.screenshot({path:`${evidence}/imported-baseline.png`});
 await page.locator('#hy-sequence').focus();await page.keyboard.press('End');await page.keyboard.press('ArrowLeft');await expect(canvas).toHaveAttribute('data-sequence',String(final.head-1));await page.locator('#hy-play').click();await expect(canvas).toHaveAttribute('data-sequence',String(final.head));const handle=await canvas.elementHandle();await page.locator('#hy-close').click();await expect.poll(async()=>handle!.evaluate(c=>(c as HTMLCanvasElement).getContext('webgl2')!.isContextLost())).toBe(true);
 expect((await readUniverse(page)).currentPlanet.objects).toEqual(live);await page.reload();await expect(page.locator('#scene-sync')).toContainText('Live');expect((await(await page.request.get('/api/history?planetId='+planet)).json()).head).toBe(final.head);checks.push('baseline, slider, play, historical deleted object, refresh, released context and unchanged live objects');
 }finally{await closeVisit(context);}
 const phoneContext=await browser.newContext({storageState:'.data/physics-browser-owner.json',viewport:{width:390,height:844},hasTouch:true,isMobile:true});const phone=await phoneContext.newPage();phone.setDefaultTimeout(12_000);phone.on('pageerror',e=>errors.push(e.message));
 try{await phone.goto('/');await expect(phone.locator('#scene-sync')).toContainText('Live');await menuAction(phone,'open-history');await expect(phone.locator('#hy-status')).toContainText('live world unchanged');await phone.locator('#hy-previous').tap();await phone.screenshot({path:`${evidence}/phone-replay.png`});expect(await phone.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);await phone.locator('#hy-close').tap();checks.push('390×844 touch replay controls and layout');}finally{await closeVisit(phoneContext);}
 const visitor=await browser.newContext();const guest=await visitor.newPage();try{await guest.goto('/');await expect(guest.locator('#begin')).toBeVisible();for(const route of ['history','history/snapshot'])expect((await guest.request.get('/api/'+route+'?planetId='+planet)).status()).toBe(403);await expect(guest.locator('#open-history')).toBeHidden();checks.push('independent visitor denied history and snapshots by server');}finally{await closeVisit(visitor);}
 expect(errors).toEqual([]);writeFileSync(`${evidence}/browser-result.json`,JSON.stringify({status:'passed',checks,pageErrors:errors},null,2)+'\n');
});
