import {test,expect} from '@playwright/test';
import {mkdirSync,writeFileSync,readFileSync,existsSync,unlinkSync} from 'node:fs';
import {menuAction,openMenu,readUniverse,closeVisit,launch,mark,pilotToBearing} from './flight-helper.ts';
import {readFeet,frame,walk} from './physics-helper.ts';
import {fieldOf,objectSeat} from '../../src/shared/terrain.ts';
import {defaultEnvironment,encodeEnvironment} from '../../src/assets/claude-geometry/terrain/env.ts';
import {SPAWN} from '../../src/shared/world.ts';
const evidence='docs/evidence/stability';
test('bounded cross-module smoke: lazy recovery, safe drafts, building physics, private history, ship return and phone controls',async({browser})=>{
 test.setTimeout(240_000);mkdirSync(evidence,{recursive:true});const checks:string[]=[],errors:string[]=[],contexts=[];let currentPage:import('@playwright/test').Page|undefined;
 const check=(message:string)=>{checks.push(message);console.log('Verified:',message);};
 const context=await browser.newContext({storageState:'.data/physics-browser-owner.json',viewport:{width:1440,height:900}});contexts.push(context);const page=await context.newPage();currentPage=page;page.setDefaultTimeout(12_000);page.on('pageerror',e=>errors.push(e.message));
 try{
 await page.goto('/');await expect(page.locator('#scene-sync')).toContainText('Live');if(existsSync('.data/stability-temporary-object.json')){const fixture=JSON.parse(readFileSync('.data/stability-temporary-object.json','utf8'));expect((await page.request.post('/api/objects/delete',{data:fixture})).ok()).toBe(true);unlinkSync('.data/stability-temporary-object.json');await page.waitForTimeout(1100);}
 let u=await readUniverse(page);expect(u.currentPlanet.mine).toBe(true);const original=u.currentPlanet,planet=original.id;
 const firstScreen=await page.evaluate(()=>performance.getEntriesByType('resource').map(e=>new URL(e.name).pathname));expect(firstScreen.some(p=>/\/(workshop-|shipyard-|history-|stage-|terrain-workshop-)/.test(p))).toBe(false);
 // One unavailable optional chunk must leave the current world and menu usable.
 await page.route('**/assets/terrain-workshop-*.js',route=>route.abort('failed'));await menuAction(page,'open-terrain');await expect(page.locator('#tool-status')).toContainText('Could not open');await expect(page.locator('#menu-dialog')).toBeVisible();await expect(page.locator('#open-terrain')).toBeEnabled();await page.unroute('**/assets/terrain-workshop-*.js');
 await page.locator('#open-terrain').click();await page.waitForFunction(()=>document.querySelector('#terrain-workshop[open]')||document.querySelector('#tool-status')?.textContent?.includes('Could not open'));
 if(!await page.locator('#terrain-workshop').isVisible()){await page.locator('#reload-tools').click();await expect(page.locator('#scene-sync')).toContainText('Live');await menuAction(page,'open-terrain');check('Browser cached the failed optional import; explicit reload recovered the saved world');}
 await expect(page.locator('#tw-status')).toContainText(/Preview only|saved terrain/);check('Optional UI chunks absent on first screen; failed import stays in pause and recovers');
 const seed=Array.from({length:80},(_,i)=>i).find(i=>original.objects.every(o=>!objectSeat(fieldOf(encodeEnvironment(defaultEnvironment('desert',i))),o,original.blueprints).problem));expect(seed).toBeDefined();await page.locator('#tw-style').selectOption('desert');await page.locator('#tw-seed').fill(String(seed));await page.locator('#tw-preview').click();await expect(page.locator('#tw-apply')).toBeEnabled();let confirmation='';page.once('dialog',async d=>{confirmation=d.message();await d.dismiss();});await page.locator('#tw-apply').click();expect(confirmation).toContain('cannot be undone');expect((await readUniverse(page)).currentPlanet).toEqual(original);await expect(page.locator('#tw-close')).toContainText('Discard preview');await page.screenshot({path:`${evidence}/terrain-preview-cancel.png`});await page.locator('#tw-close').click();check('Terrain preview and cancelled irreversible-apply confirmation leave the legacy planet unchanged');
 await menuAction(page,'open-workshop');await expect(page.locator('#ws-status')).toContainText('Library loaded');const beforeInput=await readFeet(page);await page.locator('#ws-name').fill('unsaved wasdrm draft');await page.locator('#ws-name').pressSequentially('wasd');await page.waitForTimeout(250);expect(await readFeet(page)).toEqual(beforeInput);page.once('dialog',d=>d.dismiss());await page.locator('#ws-close').click();await expect(page.locator('#workshop')).toBeVisible();await expect(page.locator('#ws-name')).toHaveValue(/unsaved/);page.once('dialog',d=>d.accept());await page.locator('#ws-close').click();await expect(page.locator('#workshop')).not.toBeVisible();
 await menuAction(page,'open-workshop');await expect(page.locator('#ws-status')).toContainText('Library loaded');await page.locator('#ws-new').click();await page.locator('#ws-name').fill('Stability floor');await page.locator('#ws-tool').selectOption('floor.deck');await page.locator('#ws-x').selectOption('2');await page.locator('#ws-z').selectOption('2');await page.locator('#ws-add').click();await page.locator('#ws-save').click();await expect(page.locator('#ws-status')).toContainText('Saved to your server library');await page.locator('#ws-place').click();await page.waitForTimeout(1000);
 for(const [x,y] of [[830,650],[530,650],[850,490],[580,460],[960,650],[620,780],[950,460],[730,600],[1040,720]]){await page.mouse.click(x,y);if(await page.locator('#save-object').isEnabled())break;}await expect(page.locator('#save-object')).toBeEnabled();await page.locator('#save-object').click();await expect(page.locator('#object-tools')).not.toBeVisible();const temp=(await readUniverse(page)).currentPlanet.objects.find(o=>!original.objects.some(a=>a.id===o.id))!;expect(temp.kind).toBe('structure');writeFileSync('.data/stability-temporary-object.json',JSON.stringify({planetId:planet,objectId:temp.id,expectedVersion:temp.version}));
 await page.locator('#built-list').selectOption(temp.id);await page.locator('#rotate-object').click();page.once('dialog',d=>d.dismiss());await page.locator('#finish-building').click();await expect(page.locator('#builder')).toBeVisible();expect((await readUniverse(page)).currentPlanet.objects.find(o=>o.id===temp.id)).toEqual(temp);await page.locator('#cancel-object').click();await page.locator('#finish-building').click();check('Blueprint keyboard input cannot move player; discard can be cancelled; saved new blueprint places; unsaved placement exit is protected');
 u=await readUniverse(page);const cabin=original.objects.find(o=>u.currentPlanet.blueprints?.[o.blueprintHash!]?.some(p=>p.part==='wall.door.open'))!,stairs=original.objects.find(o=>u.currentPlanet.blueprints?.[o.blueprintHash!]?.some(p=>p.part==='stair.straight'))!;expect(cabin).toBeTruthy();expect(stairs).toBeTruthy();const cf=frame(cabin,u.currentPlanet.blueprints![cabin.blueprintHash!]),sf=frame(stairs,u.currentPlanet.blueprints![stairs.blueprintHash!]);
 const resumed=sf.local(await readFeet(page));if(resumed.y>.1&&Math.abs(resumed.x)<.5&&resumed.z<1.6&&resumed.z> -1.7)await walk(page,f=>sf.at(0,1.9,sf.local(f).y));
 const cabinStart=cf.local(await readFeet(page));if(Math.abs(cabinStart.x)<1.25&&cabinStart.z> -1.5&&cabinStart.z<1.5){await walk(page,f=>cf.at(-.52,cabinStart.z,cf.local(f).y));await walk(page,f=>cf.at(-.52,1.95,cf.local(f).y));await walk(page,()=>cf.at(-1.9,1.95));}else if(cabinStart.z>0){if(cabinStart.x>1.25&&cabinStart.z<1.9)await walk(page,()=>cf.at(1.95,1.95));await walk(page,()=>cf.at(-1.9,1.95));}
 await walk(page,()=>cf.at(-1.9,-1.9));await walk(page,()=>cf.at(-1.9,1.9));await walk(page,()=>cf.at(-.45,1.9));await walk(page,f=>cf.at(-.52,1.28,cf.local(f).y));await walk(page,f=>cf.at(-.52,.45,cf.local(f).y));await walk(page,f=>cf.at(-.52,0,cf.local(f).y));expect(cf.local(await readFeet(page)).z).toBeLessThan(.25);await page.screenshot({path:`${evidence}/door-entry.png`});await walk(page,f=>cf.at(-.45,1.9,cf.local(f).y));await walk(page,()=>cf.at(-1.9,1.9));await walk(page,()=>cf.at(-1.9,-1.9));await walk(page,()=>sf.at(1.1,2));await walk(page,()=>sf.at(0,1.9));await walk(page,f=>sf.at(0,-1.04,sf.local(f).y));expect(sf.local(await readFeet(page)).y).toBeCloseTo(2.2,1);await page.waitForTimeout(600);const upstairs=await readFeet(page);check('Real keyboard traverses the existing open door and climbs to the saved upper floor');
 await menuAction(page,'open-history');await expect(page.locator('#hy-status')).toContainText('live world unchanged');await page.locator('#hy-previous').click();await page.locator('#hy-latest').click();await page.screenshot({path:`${evidence}/history.png`});await page.locator('#hy-close').click();expect((await readFeet(page)).radius).toBeCloseTo(upstairs.radius,4);expect((await readUniverse(page)).currentPlanet.objects.some(o=>o.id===temp.id)).toBe(true);check('History seek/close returns to the same live upper floor without restoring objects');
 await menuAction(page,'open-shipyard');await expect(page.locator('#sy-save')).toBeEnabled();await page.locator('#sy-starter').selectOption('1');await page.locator('#sy-name').fill('Local stability hauler');await page.locator('#sy-registration').fill('STB-01');await page.locator('#sy-save').click();await expect(page.locator('#sy-status')).toContainText('Saved ·');const ship=(await readUniverse(page)).player.ship!;const design=await page.locator('#sy-stage canvas').getAttribute('data-ship-design');await page.locator('#sy-name').fill('unsaved wasd');page.once('dialog',d=>d.dismiss());await page.locator('#sy-close').click();await expect(page.locator('#shipyard')).toBeVisible();page.once('dialog',d=>d.accept());await page.locator('#sy-close').click();expect((await readUniverse(page)).player.ship).toEqual(ship);
 await walk(page,f=>sf.at(0,1.9,sf.local(f).y));expect(sf.local(await readFeet(page)).y).toBeLessThan(.2);await walk(page,()=>sf.at(1.8,2.1));await walk(page,()=>SPAWN);await launch(page);await expect(page.locator('#flight-hud')).toHaveAttribute('data-ship-design',design!);await mark(page,planet);await pilotToBearing(page);await page.screenshot({path:`${evidence}/return-flight.png`});await page.locator('#land-ship').click();await page.getByRole('button',{name:'Land and explore'}).click();await expect(page.locator('#flight-hud')).not.toBeVisible();await page.reload();await expect(page.locator('#scene-sync')).toContainText('Live');expect((await readUniverse(page)).player.ship).toEqual(ship);await expect(page.locator('#world canvas')).toHaveAttribute('data-ship-design',design!);expect((await readUniverse(page)).currentPlanet.environment).toBe(original.environment);check('Ship draft discard preserves saved custom design; real descent, departure, return landing and refresh keep ship/buildings/terrain');
 await menuAction(page,'build-mode');await page.locator('#built-list').selectOption(temp.id);await page.locator('#remove-object').click();await expect(page.locator('#object-tools')).not.toBeVisible();await page.locator('#finish-building').click();expect((await readUniverse(page)).currentPlanet.objects).toEqual(original.objects);unlinkSync('.data/stability-temporary-object.json');await context.storageState({path:'.data/stability-browser-owner.json'});
 const storage=await context.storageState();await closeVisit(context);
 const mobile=await browser.newContext({storageState:storage,viewport:{width:390,height:844},isMobile:true,hasTouch:true});contexts.push(mobile);const phone=await mobile.newPage();currentPage=phone;phone.setDefaultTimeout(12_000);phone.on('pageerror',e=>errors.push(e.message));await phone.goto('/');await expect(phone.locator('#scene-sync')).toContainText('Live');await menuAction(phone,'open-shipyard');await expect(phone.locator('#sy-name')).toHaveValue(ship.design.name);const foot=await readFeet(phone);await phone.locator('#sy-name').fill('wasdrm');await phone.locator('#sy-name').pressSequentially('wasd');expect(await readFeet(phone)).toEqual(foot);phone.once('dialog',d=>d.accept());await phone.locator('#sy-close').tap();await menuAction(phone,'open-history');await expect(phone.locator('#hy-status')).toContainText('live world unchanged');await phone.screenshot({path:`${evidence}/phone-history.png`});await phone.locator('#hy-close').tap();await menuAction(phone,'open-terrain');await expect(phone.locator('#tw-status')).toContainText('Preview only');await phone.screenshot({path:`${evidence}/phone-preview.png`});await phone.locator('#tw-close').tap();expect((await readUniverse(phone)).currentPlanet.environment).toBe(original.environment);
 const b=(await phone.locator('#joystick').boundingBox())!,cdp=await mobile.newCDPSession(phone);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:b.x+b.width/2,y:b.y+b.height/2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:b.x+b.width/2+30,y:b.y+b.height/2}]});await phone.waitForTimeout(500);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();await phone.waitForTimeout(700);const mobileState=(await readUniverse(phone)).player;await phone.reload();await expect(phone.locator('#scene-sync')).toContainText('Live');expect((await readUniverse(phone)).player.position).toEqual(mobileState.position);await phone.screenshot({path:`${evidence}/phone-return.png`});expect(await phone.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);check('390×844 touch: lazy panels, protected ship draft, private replay, preview cancel, movement and refreshed save; no horizontal overflow');await closeVisit(mobile);
 const guest=await browser.newContext();contexts.push(guest);const visitor=await guest.newPage();currentPage=visitor;await visitor.goto('/');await visitor.locator('#begin').click();await openMenu(visitor);await expect(visitor.locator('#open-history')).toBeHidden();await expect(visitor.locator('#open-workshop')).toBeHidden();for(const route of ['history','history/snapshot'])expect((await visitor.request.get('/api/'+route+'?planetId='+planet)).status()).toBe(403);const library=await(await visitor.request.get('/api/blueprints?ownerId=owner')).json();expect(library).toEqual([]);expect((await visitor.request.post('/api/objects/delete',{data:{planetId:planet,objectId:cabin.id,expectedVersion:cabin.version}})).status()).toBe(403);check('Independent visitor cannot read either history endpoint, obtain owner library or delete a building');expect(errors).toEqual([]);
 writeFileSync(`${evidence}/smoke-result.json`,JSON.stringify({status:'passed',checks,pageErrors:errors,browser:browser.version(),fixtures:'Existing physics owner, original cabin and stairs retained; only the newly created temporary floor was deleted.'},null,2)+'\n');
 }catch(e){await currentPage?.screenshot({path:`${evidence}/smoke-failure.png`}).catch(()=>{});writeFileSync(`${evidence}/smoke-failure.json`,JSON.stringify({checks,pageErrors:errors,error:String(e)},null,2)+'\n');throw e;}finally{for(const c of contexts)try{await closeVisit(c);}catch{/* already closed */}}
});
