import {test,expect} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
import {menuAction,readUniverse,launch,visit,mark,pilotToBearing,closeVisit} from './flight-helper.ts';
import {fieldOf} from '../../src/shared/terrain.ts';
const evidence='docs/evidence/terrain';
test('owner previews and applies terrain, walks, refreshes, flies and lands; phone preview stays read-only',async({browser})=>{
 test.setTimeout(210_000);mkdirSync(evidence,{recursive:true});const errors:string[]=[],checks:string[]=[];
 const context=await browser.newContext({storageState:'.data/ship-browser-owner.json',viewport:{width:1440,height:900}}),page=await context.newPage();page.setDefaultTimeout(15_000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());let planet:string,saved:string;
 try{
 await page.goto('/');await expect(page.locator('#scene-sync')).toContainText('Live');let u=await readUniverse(page);
 if(u.currentPlanet.claimed&&!u.currentPlanet.mine){await visit(page);u=await readUniverse(page);}if(!u.currentPlanet.mine){await menuAction(page,'claim-planet');await expect(page.locator('#build-mode')).toBeVisible();}
 planet=(await readUniverse(page)).currentPlanet.id;const before=(await readUniverse(page)).currentPlanet.environment;
 await menuAction(page,'open-terrain');await expect(page.locator('#tw-status')).toContainText(/Preview only|saved terrain/);
 for(const style of ['ocean','desert','ice','temperate']){await page.locator('#tw-style').selectOption(style);await expect(page.locator('#tw-stage canvas')).toHaveAttribute('data-environment',new RegExp(style));await page.waitForTimeout(180);await page.screenshot({path:`${evidence}/preview-${style}.png`});expect((await readUniverse(page)).currentPlanet.environment).toBe(before);}
 await page.locator('#tw-seed').fill('');await page.locator('#tw-preview').click();await expect(page.locator('#tw-apply')).toBeDisabled();await page.locator('#tw-seed').fill('20261005');await page.locator('#tw-style').selectOption('desert');await page.locator('#tw-preview').click();saved=(await page.locator('#tw-stage canvas').getAttribute('data-environment'))!;
 if(saved!==before){await page.route('**/api/terrain/apply',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Intentional terrain save failure check.'})}));await page.locator('#tw-apply').click();await expect(page.locator('#tw-status')).toContainText('Intentional');expect((await readUniverse(page)).currentPlanet.environment).toBe(before);await page.unroute('**/api/terrain/apply');await page.locator('#tw-apply').click();await expect(page.locator('#tw-status')).toContainText('Terrain saved');checks.push('failed save preserves live environment; explicit owner apply');}
 expect((await readUniverse(page)).currentPlanet.environment).toBe(saved);checks.push('four independent previews; blank seed rejected; saved environment retained');
 const handle=await page.locator('#tw-stage canvas').elementHandle();await page.locator('#tw-close').click();await expect.poll(async()=>handle!.evaluate(c=>(c as HTMLCanvasElement).getContext('webgl2')!.isContextLost())).toBe(true);await expect(page.locator('#world canvas')).toHaveAttribute('data-terrain-id',fieldOf(saved).id+':graded');
 const start=(await readUniverse(page)).player.position;await page.keyboard.down('w');await page.waitForTimeout(1100);await page.keyboard.up('w');await page.keyboard.down('d');await page.waitForTimeout(650);await page.keyboard.up('d');await page.waitForTimeout(1000);
 const walked=(await readUniverse(page)).player;expect(Math.hypot(...walked.position.map((v,i)=>v-start[i]))).toBeGreaterThan(.1);expect(walked.ground!.radius).toBeCloseTo(10+fieldOf(saved).heightAt(walked.position),2);await page.screenshot({path:`${evidence}/desktop-ground.png`});
 await page.reload();await expect(page.locator('#scene-sync')).toContainText('Live');expect((await readUniverse(page)).currentPlanet.environment).toBe(saved);expect(Math.hypot(...(await readUniverse(page)).player.position.map((v,i)=>v-walked.position[i]))).toBeLessThan(.01);checks.push('real W/D surface movement follows shared field, released preview context, refresh retains position/environment');
 await menuAction(page,'build-mode');await page.waitForTimeout(950);const originalObjects=(await readUniverse(page)).currentPlanet.objects;await page.getByRole('button',{name:'Add lamp',exact:true}).click();for(const [x,y] of [[600,590],[830,550],[540,510],[960,570],[680,430],[820,660],[550,700],[900,700],[700,740],[460,610],[1000,480],[700,420],[590,430],[980,690],[730,570]]){await page.mouse.click(x,y);if(await page.locator('#save-object').isEnabled())break;}
 await expect(page.locator('#save-object')).toBeEnabled();await page.locator('#save-object').click();await expect(page.locator('#object-tools')).not.toBeVisible();await page.locator('#finish-building').click();const temporaryLamp=(await readUniverse(page)).currentPlanet.objects.find(o=>!originalObjects.some(old=>old.id===o.id))!;const history=await(await page.request.get('/api/history/snapshot?planetId='+planet)).json();expect(history.environment).toBe(saved);
 await menuAction(page,'open-history');await expect(page.locator('#hy-status')).toContainText('live world unchanged');await page.screenshot({path:`${evidence}/terrain-history.png`});await page.locator('#hy-close').click();checks.push('build on generated ground; private history replays same saved terrain');await menuAction(page,'build-mode');await page.locator('#built-list').selectOption(temporaryLamp.id);await page.locator('#remove-object').click();await expect(page.locator('#object-tools')).not.toBeVisible();await page.locator('#finish-building').click();
 await launch(page);await page.waitForTimeout(700);await page.screenshot({path:`${evidence}/orbit.png`});await page.reload();await expect(page.locator('#flight-hud')).toBeVisible();expect((await readUniverse(page)).currentPlanet.environment).toBe(saved);await mark(page,planet);await pilotToBearing(page);await page.screenshot({path:`${evidence}/orbit-return.png`});await page.locator('#land-ship').click();await page.getByRole('button',{name:'Land and explore'}).click();await expect(page.locator('#flight-hud')).not.toBeVisible();await page.waitForTimeout(500);const landed=(await readUniverse(page)).player;expect(landed.ground!.radius).toBeCloseTo(10+fieldOf(saved).heightAt(landed.position),2);await page.screenshot({path:`${evidence}/landed.png`});await context.storageState({path:'.data/terrain-browser-owner.json'});checks.push('actual boarding, launch, refresh in flight, keyboard return flight, dry-pad landing');
 }catch(e){await page.screenshot({path:`${evidence}/repeat-run-failure.png`}).catch(()=>{});writeFileSync(`${evidence}/repeat-run-result.json`,JSON.stringify({checks,pageErrors:errors,error:String(e)},null,2)+'\n');throw e;}finally{await closeVisit(context);}
 const mobile=await browser.newContext({storageState:'.data/terrain-browser-owner.json',viewport:{width:390,height:844},isMobile:true,hasTouch:true}),phone=await mobile.newPage();phone.setDefaultTimeout(15_000);phone.on('pageerror',e=>errors.push(e.message));
 try{await phone.goto('/');await expect(phone.locator('#scene-sync')).toContainText('Live');await menuAction(phone,'open-terrain');await pageClosedPreview(phone);
 await phone.locator('#tw-style').selectOption('ocean');await expect(phone.locator('#tw-stage canvas')).toHaveAttribute('data-environment',/ocean/);await phone.screenshot({path:`${evidence}/phone-preview.png`});await phone.locator('#tw-close').click();expect((await readUniverse(phone)).currentPlanet.environment).toBe(saved);
 const b=(await phone.locator('#joystick').boundingBox())!,cdp=await mobile.newCDPSession(phone);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:b.x+b.width/2,y:b.y+b.height/2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:b.x+b.width/2+30,y:b.y+b.height/2}]});await phone.waitForTimeout(500);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();await phone.waitForTimeout(800);await phone.screenshot({path:`${evidence}/phone-ground.png`});expect((await readUniverse(phone)).player.ground!.grounded).toBe(true);checks.push('390×844 phone preview, close without applying, real touch movement');}finally{await closeVisit(mobile);}
 const visitor=await browser.newContext(),v=await visitor.newPage();try{await v.goto('/');const denied=await v.request.post('/api/terrain/apply',{data:{planetId:planet,environment:saved,expectedRevision:0}});expect(denied.status()).toBe(403);checks.push('independent visitor HTTP apply denied 403');}finally{await closeVisit(visitor);}
 expect(errors).toEqual([]);writeFileSync(`${evidence}/browser-result.json`,JSON.stringify({status:'passed',planet,checks,pageErrors:errors,viewport:'1440×900 and 390×844',browser:browser.version()},null,2)+'\n');
});
async function pageClosedPreview(page:import('@playwright/test').Page){await expect(page.locator('#tw-status')).toContainText('saved terrain');}

test('new private blueprint ghost fits generated terrain, and a flooding preview is refused by UI and server',async({browser})=>{
 test.setTimeout(60_000);const context=await browser.newContext({storageState:'.data/terrain-browser-owner.json',viewport:{width:1920,height:1080}}),page=await context.newPage(),errors:string[]=[];page.setDefaultTimeout(10_000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 try{
 await page.goto('/');await expect(page.locator('#scene-sync')).toContainText('Live');await menuAction(page,'open-workshop');await expect(page.locator('#ws-save')).toBeEnabled();await page.locator('#ws-new').click();await page.locator('#ws-name').fill('Terrain footing check');await page.locator('#ws-tool').selectOption('floor.deck');await page.locator('#ws-x').selectOption('2');await page.locator('#ws-z').selectOption('2');await page.locator('#ws-add').click();await page.locator('#ws-save').click();await expect(page.locator('#ws-status')).toContainText('Saved to your server library');await page.locator('#ws-place').click();await expect(page.locator('#builder')).toBeVisible();await page.waitForTimeout(900);
 for(const [x,y] of [[820,740],[1120,725],[700,620],[1230,650],[920,550],[1060,540],[700,780],[1190,470],[850,455],[1100,840]]){await page.mouse.click(x,y);if(await page.locator('#save-object').isEnabled())break;}
 await expect(page.locator('#save-object')).toBeEnabled();await page.locator('#save-object').click();await expect(page.locator('#object-tools')).not.toBeVisible();await page.screenshot({path:`${evidence}/blueprint-on-terrain.png`});await page.locator('#finish-building').click();const before=(await readUniverse(page)).currentPlanet;expect(before.objects.some(o=>o.kind==='structure')).toBe(true);
 const {defaultEnvironment,encodeEnvironment}=await import('../../src/assets/claude-geometry/terrain/env.ts'),{objectSeat}=await import('../../src/shared/terrain.ts');const seed=Array.from({length:100},(_,i)=>i).find(i=>before.objects.some(o=>objectSeat(fieldOf(encodeEnvironment(defaultEnvironment('ocean',i))),o,before.blueprints).problem));expect(seed).toBeDefined();
 await menuAction(page,'open-terrain');await expect(page.locator('#tw-status')).toContainText('saved terrain');await page.locator('#tw-style').selectOption('ocean');await page.locator('#tw-seed').fill(String(seed));await page.locator('#tw-preview').click();await expect(page.locator('#tw-apply')).toBeDisabled();await expect(page.locator('#tw-check')).toContainText(/under water|ground drops/);await page.screenshot({path:`${evidence}/restrict-conflict.png`});const response=await page.request.post('/api/terrain/apply',{data:{planetId:before.id,environment:encodeEnvironment(defaultEnvironment('ocean',seed!)),expectedRevision:before.revision}});expect(response.status()).toBe(409);expect((await readUniverse(page)).currentPlanet).toEqual(before);await page.locator('#tw-close').click();expect(errors).toEqual([]);writeFileSync(`${evidence}/restriction-result.json`,JSON.stringify({status:'passed',checks:['real UI creates/saves a one-deck blueprint and places its new ghost on generated terrain','conflicting ocean preview disables apply','direct owner apply returns 409; all current planet objects/transforms and environment unchanged'],pageErrors:errors},null,2)+'\n');
 }finally{await closeVisit(context);}
});
