import { expect, it } from 'vitest';
import { randomUUID } from 'node:crypto';
import { mkdtempSync, rmSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { DatabaseSync } from 'node:sqlite';
import { openStore } from '../src/server/store.ts';
import { normalize, SPAWN } from '../src/shared/world.ts';
const point = normalize([.45, 1, .4]);
it('enforces one home per identity, one owner per planet, owner-only edits and idempotent commands', () => {
  const s = openStore(':memory:'); s.create('a'); s.create('b');
  const [p1, p2] = s.universe('a').planets.filter(p => p.kind === 'garden');
  s.claim('a', p1.id); s.claim('a', p1.id);
  expect(() => s.claim('b', p1.id)).toThrow('already');
  expect(() => s.claim('a', p2.id)).toThrow('already');
  s.claim('b', p2.id);
  expect(() => s.db.prepare('UPDATE planets SET owner_id=? WHERE id=?').run('a',p2.id)).toThrow();
  const body = { planetId: p1.id, objectId: randomUUID(), kind: 'tree', position: point, rotation: 0 };
  expect(() => s.createObject('b', body)).toThrow('Only');
  s.createObject('a', body); s.createObject('a', body);
  s.visit('b', p1.id); expect(s.universe('b').currentPlanet.objects).toHaveLength(1);
  expect(s.universe('b').currentPlanet.mine).toBe(false);
  const update = { planetId: p1.id, objectId: body.objectId, position: point, rotation: 1, expectedVersion: 1 };
  expect(() => s.updateObject('b', update)).toThrow('Only');
  s.updateObject('a', update); s.updateObject('a', update);
  expect(s.universe('b').currentPlanet.objects[0].version).toBe(2);
  expect(() => s.updateObject('a', { ...update, rotation: 2 })).toThrow('another tab');
  const remove = { planetId: p1.id, objectId: body.objectId, expectedVersion: 2 };
  expect(() => s.removeObject('b', remove)).toThrow('Only');
  expect(() => s.removeObject('a', { ...remove, expectedVersion: 1 })).toThrow('another tab');
  s.removeObject('a', remove); s.removeObject('a', remove);
  expect(() => s.createObject('a', body)).toThrow('removed');
  expect(s.universe('b').currentPlanet.objects).toHaveLength(0); s.close();
});
it('rejects unknown fields, invalid models/placement/rotation, overlap and forged ownership', () => {
  const s = openStore(':memory:'); s.create('a');
  const p = s.universe('a').planets.find(p => p.kind === 'garden')!; s.claim('a', p.id);
  const body = { planetId: p.id, objectId: randomUUID(), kind: 'tree', position: point, rotation: 0 };
  for (const patch of [{ ownerId: 'a' }, { kind: '__proto__' }, { position: [0, 0, 0] }, { position: [NaN, 1, 0] }, { rotation: Infinity }, { rotation: -1 }, { position: SPAWN }, { objectId: 'x' }])
    expect(() => s.createObject('a', { ...body, ...patch })).toThrow();
  s.createObject('a', body);
  expect(() => s.createObject('a', { ...body, objectId: randomUUID() })).toThrow('too close');
  expect(() => s.claim('a', 'hub')).toThrow('everyone'); s.close();
});
it('backs up and migrates v1 without losing old state; planets, scenes and visits survive reopen', () => {
  const dir = mkdtempSync(join(tmpdir(), 'little-worlds-')), path = join(dir, 'world.sqlite');
  const legacy = new DatabaseSync(path);
  legacy.exec(`CREATE TABLE players (id TEXT PRIMARY KEY, character TEXT, quest TEXT, position TEXT, deliveries INTEGER, revision INTEGER, moved_at INTEGER); PRAGMA user_version=1;`);
  legacy.prepare('INSERT INTO players VALUES (?,?,?,?,?,?,?)').run('a', 'sky', 'carrying', JSON.stringify(SPAWN), 0, 17, 0); legacy.close();
  const s = openStore(path); expect(s.migrationBackup && existsSync(s.migrationBackup)).toBe(true);
  const backup = new DatabaseSync(s.migrationBackup!); expect(backup.prepare('SELECT revision,character,quest FROM players').get()).toMatchObject({ revision: 17, character: 'sky', quest: 'carrying' }); backup.close();
  expect(s.state('a')).toMatchObject({ character: 'sky', quest: 'carrying', revision: 17, position: SPAWN, planetId: 'hub' });
  const p = s.universe('a').planets.find(p => p.kind === 'garden')!; s.claim('a', p.id); s.visit('a', p.id);
  s.createObject('a', { planetId: p.id, objectId: randomUUID(), kind: 'tree', position: point, rotation: 0 });
  expect(() => s.interact('a', 'deliver')).toThrow('Harbour');
  const state = s.state('a'); s.close();
  const reopened = openStore(path); expect(reopened.migrationBackup).toBeNull(); expect(reopened.state('a')).toEqual(state);
  expect(reopened.universe('a').currentPlanet.objects).toHaveLength(1);
  reopened.visit('a', 'hub'); expect(reopened.state('a')).toMatchObject({ position: SPAWN, quest: 'carrying', character: 'sky' });
  reopened.close(); rmSync(dir, { recursive: true });
});
it('enforces the object budget and fences stale movement after changing planets', () => {
  const s=openStore(':memory:');s.create('a');const p=s.universe('a').planets.find(p=>p.kind==='garden')!;s.claim('a',p.id);
  const body={planetId:p.id,objectId:randomUUID(),kind:'path',position:point,rotation:0};
  for(let i=0;i<64;i++)s.createObject('a',{...body,objectId:i?randomUUID():body.objectId});
  expect(()=>s.createObject('a',{...body,objectId:randomUUID()})).toThrow('64');
  s.createObject('a',body);s.visit('a',p.id);expect(s.universe('a').currentPlanet.objects).toHaveLength(64);
  expect(()=>s.move('a',SPAWN,Date.now(),'hub')).toThrow('another planet');
  expect(()=>s.move('a',SPAWN)).toThrow('another planet');s.move('a',SPAWN,Date.now(),p.id);s.close();
});
